"use client";

import { useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Briefcase, ChevronRight, Download, Droplets, Images, LayoutDashboard, LogOut, Menu, Newspaper, Zap } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

const navItems = [{ name: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard }, { name: "Projects", href: "/admin/projects", icon: Zap }, { name: "News", href: "/admin/news", icon: Newspaper }, { name: "Reports", href: "/admin/downloads", icon: Download }, { name: "Careers", href: "/admin/careers", icon: Briefcase }, { name: "Gallery", href: "/admin/gallery", icon: Images }];

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [sidebarOpen, setSidebarOpen] = useState(false);
  if (pathname === "/admin/login") return <>{children}</>;
  const logout = async () => { await createSupabaseBrowserClient().auth.signOut(); router.replace("/admin/login"); router.refresh(); };
  return <div className="flex h-screen overflow-hidden bg-[#F7FAFB] font-sans">{sidebarOpen && <div className="fixed inset-0 z-20 bg-black/50 lg:hidden" onClick={() => setSidebarOpen(false)} />}<aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col bg-[#0B3D5C] text-white transition-transform duration-300 lg:static ${sidebarOpen ? "translate-x-0" : "-translate-x-full lg:translate-x-0"}`}><div className="flex items-center gap-3 border-b border-white/10 px-6 py-5"><div className="rounded-lg bg-[#1A8FA3] p-2"><Droplets className="h-5 w-5" /></div><div><p className="font-bold">Gumu Khola</p><p className="text-xs text-white/50">Admin Panel</p></div></div><nav className="flex-1 space-y-1 overflow-y-auto px-4 py-6">{navItems.map((item) => { const Icon = item.icon; const active = pathname.startsWith(item.href); return <Link key={item.href} href={item.href} onClick={() => setSidebarOpen(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${active ? "bg-[#1A8FA3]" : "text-white/70 hover:bg-white/10 hover:text-white"}`}><Icon className="h-5 w-5" />{item.name}{active && <ChevronRight className="ml-auto h-4 w-4" />}</Link>; })}</nav><div className="border-t border-white/10 px-4 pb-6 pt-4"><button type="button" onClick={logout} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-white/70 hover:bg-red-500/20 hover:text-red-300"><LogOut className="h-5 w-5" />Logout</button></div></aside><div className="flex flex-1 flex-col overflow-hidden"><header className="flex h-16 flex-none items-center border-b border-[#E4EAEE] bg-white px-6"><button type="button" onClick={() => setSidebarOpen(true)} className="rounded-md p-2 text-[#1E2A33] hover:bg-[#E4EAEE] lg:hidden"><Menu className="h-5 w-5" /></button><p className="hidden text-sm font-medium text-[#1E2A33] lg:block">{navItems.find((item) => pathname.startsWith(item.href))?.name ?? "Admin"}</p><div className="ml-auto flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#0B3D5C] text-xs font-bold text-white">A</div><span className="hidden text-sm font-medium text-[#1E2A33] sm:block">Admin</span></div></header><main className="flex-1 overflow-y-auto p-6">{children}</main></div></div>;
}
