import Hero from "@/components/ui/Hero";
import StatsCounter from "@/components/ui/StatsCounter";
import FeaturedProjects from "@/components/projects/FeaturedProjects";
import GalleryGrid from "@/components/gallery/GalleryGrid";
import { stats } from "@/lib/data";
import Link from "next/link";
import { ArrowRight, ChevronDown, Leaf, Zap, ShieldCheck } from "lucide-react";

const faqs = [
  {
    question: "What is the Gumu Khola Hydropower Project?",
    answer: "The Gumu Khola Hydropower Project is a renewable energy project being developed by Gumukhola Bhayakure Hydropower Limited. The project aims to generate clean and sustainable electricity by utilizing the perennial flow of the Gumu Khola River in Dolakha District, Nepal.",
  },
  {
    question: "Where is the project located?",
    answer: "The project is located in Dolakha District, Nepal, within the former Lamidanda and Sunkhani VDCs. The powerhouse is approximately 1 km upstream from the confluence of Gumu Khola and Tamakoshi Khola.",
  },
  {
    question: "Who is developing the project?",
    answer: "The project is being developed by Gumukhola Bhayakure Hydropower Limited, a public limited company dedicated to developing renewable hydropower projects in Nepal.",
  },
  {
    question: "Is Gumu Khola a seasonal river?",
    answer: "No. According to the engineering report, Gumu Khola is a perennial river with reliable water flow throughout the year, supported by numerous natural springs.",
  },
  {
    question: "How can the project site be accessed?",
    answer: "The project can be reached by road from Kathmandu to Charikot and then to the project site, with a total travel distance of approximately 165 km.",
  },
  {
    question: "What are the major components of the hydropower project?",
    answer: "The project includes a weir, intake, settling basin, water conveyance system, penstock, and powerhouse. These facilities are located on the left bank of Gumu Khola.",
  },
  {
    question: "Does the project support environmental sustainability?",
    answer: "The project is located in an area rich in forests, natural vegetation, wildlife, and perennial water resources. The development aims to utilize renewable hydropower resources while contributing to Nepal's clean energy future.",
  },
  {
    question: "How will the electricity generated by the project be transmitted?",
    answer: "The generated electricity is planned to be evacuated to Nepal's Integrated National Power System (INPS) through the 132/33 kV Singati Substation, which is under construction.",
  },
  {
    question: "When did the company become a Public Limited Company?",
    answer: "Gumukhola Bhayakure Hydropower was officially converted from a Private Limited Company to a Public Limited Company on 22 June 2026.",
  },
  {
    question: "Why is the Gumu Khola Hydropower Project important?",
    answer: "The project is expected to contribute to Nepal's renewable energy development by utilizing local water resources to produce clean electricity, strengthen the national power supply, and support sustainable economic growth. This answer is based on the project's purpose and location; the uploaded documents do not quantify expected power generation or economic impacts.",
  },
];

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <Hero 
        title="Powering Gumu Khola with Clean, Renewable Hydropower"
        subtitle="We harness the power of nature to provide sustainable, reliable energy for generations to come."
        imageSrc="https://images.unsplash.com/photo-1549424840-7ab3fba0132b?auto=format&fit=crop&q=80"
        ctaText="Explore Our Projects"
        ctaLink="/projects"
        isMain={true}
      />

      <StatsCounter stats={stats} />

      {/* Introduction Section */}
      <section className="py-20 bg-background">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <h2 className="text-3xl font-bold text-primary mb-6">Committed to a Sustainable Future</h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              At Gumu Khola Hydropower, we believe in the harmony between technological advancement and environmental preservation. Our run-of-river projects are designed to minimize ecological impact while maximizing energy output.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="p-6 bg-card rounded-2xl border border-border text-center">
              <div className="w-14 h-14 bg-secondary/10 rounded-full flex items-center justify-center mx-auto mb-6">
                <Leaf className="w-7 h-7 text-secondary" />
              </div>
              <h3 className="text-xl font-bold mb-3">Eco-Friendly</h3>
              <p className="text-muted-foreground">Minimal reservoir impact, preserving local ecosystems and river health.</p>
            </div>
            
            <div className="p-6 bg-card rounded-2xl border border-border text-center">
              <div className="w-14 h-14 bg-secondary/10 rounded-full flex items-center justify-center mx-auto mb-6">
                <Zap className="w-7 h-7 text-secondary" />
              </div>
              <h3 className="text-xl font-bold mb-3">High Efficiency</h3>
              <p className="text-muted-foreground">Utilizing state-of-the-art turbines and generators for maximum power extraction.</p>
            </div>

            <div className="p-6 bg-card rounded-2xl border border-border text-center">
              <div className="w-14 h-14 bg-secondary/10 rounded-full flex items-center justify-center mx-auto mb-6">
                <ShieldCheck className="w-7 h-7 text-secondary" />
              </div>
              <h3 className="text-xl font-bold mb-3">Reliability</h3>
              <p className="text-muted-foreground">Consistent baseload power supporting the regional grid year-round.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Featured Projects */}
      <section className="py-20 bg-slate-50 dark:bg-slate-900/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-end mb-12">
            <div>
              <h2 className="text-3xl font-bold text-primary dark:text-white mb-4">Featured Projects</h2>
              <p className="text-muted-foreground max-w-2xl">Discover how our infrastructure is powering communities today and building capacity for tomorrow.</p>
            </div>
            <Link href="/projects" className="hidden md:flex items-center text-secondary hover:text-primary transition-colors font-semibold">
              View All <ArrowRight className="w-5 h-5 ml-2" />
            </Link>
          </div>

          <FeaturedProjects />
          
          <div className="mt-10 md:hidden text-center">
            <Link href="/projects" className="inline-flex items-center text-secondary hover:text-primary transition-colors font-semibold">
              View All Projects <ArrowRight className="w-5 h-5 ml-2" />
            </Link>
          </div>
        </div>
      </section>

      {/* Gallery */}
      <section className="bg-background py-20">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mb-12 flex items-end justify-between">
            <div>
              <h2 className="mb-4 text-3xl font-bold text-primary">Gallery</h2>
              <p className="max-w-2xl text-muted-foreground">Explore our projects, landscapes, and community work.</p>
            </div>
            <Link href="/gallery" className="hidden font-semibold text-secondary transition-colors hover:text-primary md:flex">
              View Gallery <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
          </div>
          <GalleryGrid limit={3} />
        </div>
      </section>

      {/* Frequently Asked Questions */}
      <section className="bg-slate-50 py-20 dark:bg-slate-900/50">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="mb-12 text-center">
            <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-secondary">FAQ</p>
            <h2 className="text-3xl font-bold text-primary dark:text-white">Frequently Asked Questions</h2>
            <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">Learn more about the Gumu Khola Hydropower Project and its role in Nepal&apos;s clean energy future.</p>
          </div>

          <div className="space-y-3">
            {faqs.map((faq) => (
              <details key={faq.question} className="group rounded-xl border border-border bg-card px-5 open:border-secondary/40">
                <summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-5 text-left font-semibold text-primary marker:hidden dark:text-white">
                  {faq.question}
                  <ChevronDown className="h-5 w-5 shrink-0 text-secondary transition-transform group-open:rotate-180" />
                </summary>
                <p className="pb-5 pr-8 leading-relaxed text-muted-foreground">{faq.answer}</p>
              </details>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
